### ISSUE TITLE
Remove console.log calls

### ISSUE THREAD

**Issue by redclov3r** [mikolalysenko/vectorize-text#3]
Maybe they can be deactivated by default and activated with a debug setting, if they are really needed?

The output clutters my console and keeps breaking iOS remote debugging sessions

**Comment by mikolalysenko** [comment]
Whoops!  That shouldn't be there!  Must've accidentally left them in

**Comment by mikolalysenko** [comment]
Fixed now

**Comment by redclov3r** [comment]
Wow, that was quick! Thank you very much :+1:
